name: reddit_post
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  video_player: ^2.7.2
  floating_pullup_card: ^1.2.0
  native_video_player: ^1.3.0
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.2
  flutter_animate: ^4.2.0+1
  provider: ^6.0.5
  share_plus: ^7.1.0
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "ic_launcher"

  image_path: "assets/reddit.png"
  min_sdk_android: 21 



flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/videos/
    - assets/pics/

  fonts:
    - family: Arimo
      fonts:
        - asset: assets/fonts/Arimo/Arimo-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Arimo/Arimo-VariableFont_wght.ttf
      

          style: italic
