import '../../models/comment.dart';

List<Comment> comments = [
  Comment(
    id: 1,
    username: "John123",
    pic: "assets/pics/p1.png",
    replies: [],
    text: "nice cats",
    votes: 5,
  ),
  Comment(
    id: 2,
    username: "Emma456",
    pic: "assets/pics/p2.png",
    replies: [],
    text: "cool cats!",
    votes: 4,
  ),
  Comment(
    id: 3,
    username: "Michael789",
    pic: "assets/pics/p3.png",
    replies: [],
    text: "Beautiful photo!",
    votes: 7,
  ),
  Comment(
    id: 4,
    username: "Sophia012",
    pic: "assets/pics/p4.png",
    replies: [],
    text: "Adorable kittens!",
    votes: 6,
  ),
  Comment(
    id: 5,
    username: "David345",
    pic: "assets/pics/p5.png",
    replies: [],
    text: "Love the composition!",
    votes: 9,
  ),
  Comment(
    id: 6,
    username: "Emily678",
    pic: "assets/pics/p6.png",
    replies: [],
    text: "Great shot!",
    votes: 3,
  ),
  Comment(
    id: 7,
    username: "Oliver901",
    pic: "assets/pics/p7.png",
    replies: [],
    text: "Cute kittens!",
    votes: 8,
  ),
  Comment(
    id: 8,
    username: "Ava234",
    pic: "assets/pics/p8.png",
    replies: [],
    text: "Amazing work!",
    votes: 10,
  ),
  Comment(
    id: 9,
    username: "Noah567",
    pic: "assets/pics/p9.png",
    replies: [],
    text: "So adorable!",
    votes: 7,
  ),
  Comment(
    id: 10,
    username: "Isabella890",
    pic: "assets/pics/p10.png",
    replies: [],
    text: "Incredible photo!",
    votes: 12,
  ),
  Comment(
    id: 11,
    username: "William123",
    pic: "assets/pics/p11.png",
    replies: [],
    text: "Lovely cats!",
    votes: 6,
  ),
  Comment(
    id: 12,
    username: "Mia456",
    pic: "assets/pics/p12.png",
    replies: [],
    text: "Fantastic shot!",
    votes: 11,
  ),
];
